name: Release
on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build spinjs
    runs-on: "ubuntu-latest"
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: karthik2804/gh-auto-pr-source
          path: my-tools

      - name: create PR step
        shell: bash
        run: |
          ls 
          echo "hello there"
          ls my-tools
          cd my-tools/manifests/js2wasm
          mv js2wasm.json js2wasm-old.json
          cp ../../../main/test.json js2wasm.json
          cd ../../
          ls
          pwd
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MY_PERSONAL_TOKEN }}
          path: my-tools